geertmeersman/youfone

- .github/PULL_REQUEST_TEMPLATE.md
- .github/labels.yml
- .pre-commit-config.yaml
- custom_components/youfone/__init__.py
- custom_components/youfone/client.py
> Client header improvements

- custom_components/youfone/client.py
> Round usage percentages

- custom_components/youfone/client.py
- custom_components/youfone/config_flow.py
- custom_components/youfone/sensor.py
> Fix Youcoin sensor type, fixes #17

- custom_components/youfone/config_flow.py
- custom_components/youfone/translations/en.json
- custom_components/youfone/translations/nl.json
> Config flow improvement for language option

- .github/workflows/bump_version_and_release.yml
- custom_components/youfone/client.py
> The missing point :-)

- .github/labels.yml
- .github/scripts/get_new_version.py
- .github/scripts/pr_extract_labels.py
- .github/workflows/pr-checker.yml
- .pre-commit-config.yaml
- .ruff.toml
- custom_components/youfone/client.py
> Round % values & refactoring

- custom_components/youfone/sensor.py
> refactor: suggested_display_precision=0

- .gitignore
- .pre-commit-config.yaml
- custom_components/youfone/client.py
- custom_components/youfone/utils.py
> fix: Don't trust the Youfone percentage, calculate it!

- README.md
> docs: debugging docs in Readme

- .github/scripts/get_new_version.py
- .github/workflows/bump_version_and_prerelease.yml
- custom_components/youfone/client.py
- custom_components/youfone/utils.py
> fix: improve the genius youfone amount notation

- .github/release-drafter-beta.yml
> feat: Beta release drafter

- .github/scripts/get_new_version.py
> fix: beta version fetcher

- custom_components/youfone/config_flow.py
- custom_components/youfone/translations/en.json
- custom_components/youfone/translations/fr.json
- custom_components/youfone/translations/nl.json
> fix: Add username change in config flow options

- .github/workflows/bandit.yml
- .github/workflows/bump_version_and_prerelease.yml
- .github/workflows/bump_version_and_release.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/lint.yml
- .github/workflows/pr-checker.yml
- .github/workflows/stale.yaml
- .github/workflows/synchronize-labels.yml
- .github/workflows/validate.yml
> refactor: workflows

- .github/release-drafter.yml
- README.md
> docs: repo finally added to HACS

- README.md
> docs: troubleshooting

- custom_components/youfone/translations/pt.json
- [ X] My code follows the code style of this project.
- [ X] My change requires a change to the documentation.
- [ X] I have updated the documentation accordingly.
> Feature: Create pt.json

- custom_components/youfone/client.py
> fix: ignore youcoins when the partner service is unavailable

- custom_components/youfone/client.py
- custom_components/youfone/const.py
> fix: Youcoins NL url

- custom_components/youfone/client.py
> fix: 418 issue, fixes #57

- custom_components/youfone/const.py
> fix: increased update interval to 1 hour & format to f-string conversion

- custom_components/youfone/__init__.py
- custom_components/youfone/client.py
- custom_components/youfone/const.py
> fix: sleep added between requests, trying to avoid IP blacklisting

- custom_components/youfone/client.py
- custom_components/youfone/utils.py
> fix: price int fix, references #73

- .github/workflows/bump_version_and_release.yml
- custom_components/youfone/config_flow.py
- custom_components/youfone/translations/en.json
- custom_components/youfone/translations/fr.json
- custom_components/youfone/translations/nl.json
- custom_components/youfone/translations/pt.json
> fix: move release zip

- custom_components/youfone/client.py
- custom_components/youfone/const.py
- custom_components/youfone/utils.py
> fix: slow down http calls, mask sensitive fields and remove youcoin calls (temporarily) references #86

- custom_components/youfone/utils.py
> fix: jsonpath removed

- custom_components/youfone/client.py
> fix: round to 1 decimal for percentages

- custom_components/youfone/__init__.py
- custom_components/youfone/binary_sensor.py
- custom_components/youfone/client.py
- custom_components/youfone/const.py
- custom_components/youfone/entity.py
- custom_components/youfone/sensor.py
New binary sensors when data/voice percentage is higher than the period percentage
> feat: store implemented and data+voice alarm binary sensors

- custom_components/youfone/__init__.py
- custom_components/youfone/binary_sensor.py
- custom_components/youfone/sensor.py
> fix: Youfoneitem casting fix

- README.md
- custom_components/youfone/sensor.py
> feat: remaining_days sensor NL

- custom_components/youfone/sensor.py
> fix: unit of measurement %

- custom_components/youfone/manifest.json
- custom_components/youfone/sensor.py
> feat: subscription price sensor + bump aioyoufone

- custom_components/youfone/sensor.py
> fix: device_class monetary for price

- custom_components/youfone/__init__.py
- custom_components/youfone/manifest.json
> fix: aioyoufone client version

- README.md
- custom_components/youfone/config_flow.py
> refactor: markdown & config flow

- custom_components/youfone/config_flow.py
> fix: config flow

- custom_components/youfone/binary_sensor.py
- custom_components/youfone/const.py
> fix: re-enable binary alarm sensors for BE

- custom_components/youfone/const.py
> fix: youfone => yoin for BE

- custom_components/youfone/__init__.py
- custom_components/youfone/config_flow.py
> chore: ignore type for vscode

- custom_components/youfone/manifest.json
> fix: voice/data position, bump aioyoufone

- custom_components/youfone/sensor.py
> fix: voice/data sensor value = calculated value
